name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make mlrate
      run: cd mlrate/src && make
    - name: configure
      run: cd src && ./configure --prefix=/home/nngs
    - name: make
      run: cd src && make
    - name: make check
      run: cd src && make check
    - name: make distcheck
      run: cd src && make distcheck
